print("Hello World!")
print("Hello Again")
print("I like typing this.")
print("This is fun.")
print('Yay !Printing.')
print("I'd much rather you 'not'.")
print('I "said" do not touch this.')
print('hello \n world')
print('hello \t world')
print("Get with the program")
print("Eliezer Brown")
print('Item \t price')
print('Apple \t 1.75')
print("Orange \t 3.50")
print("Banana \t 2.25")
print("Total \t 9.00")
